# shared profile
spring:
  profiles:
    active: test
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stelpolvo.video.dao
video:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592090000