spring:
  datasource:
    url: jdbc:mysql:///video?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: localdocker
    driver-class-name: com.mysql.cj.jdbc.Driver

rocketmq:
  producer:
    moments:
      name: localhost:9876

swagger:
  enabled: true