spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: localdocker
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
  http:
    multipart:
      max-file-size: 250Mb
      max-request-size: 3000Mb
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 600s
    socket-timeout: 600s

rocketmq:
  producer:
    moments:
      name: localhost:9876


swagger:
  enabled: true

fdfs:
  tracker-list: localhost:22122
  http:
      storage-address: localhost:22122